title: MUME Wiki
description: A community wiki and guide to surviving in Multi-Users in Middle-earth.
theme: jekyll-theme-cayman

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:path/

exclude:
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
